import { Inter } from "next/font/google";
import "../styles/globals.css";

import NavBar from "@/components/navbar/NavBar";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <main className="min-h-screen bg-primary">
          <NavBar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
